import React from "react";
import magneto3 from "../../../assets/magimg3.png"; // ← استيراد الصورة

export default function Magneto3() {
  return (
    <section className="w-full bg-[#ffffff] py-12 px-6 md:px-12 lg:px-24 font-[Open_Sans]">
      
      {/* ----- الصف العلوي: العنوان + النص + الصورة ----- */}
      <div className="max-w-[1300px] mx-auto grid grid-cols-1 lg:grid-cols-2 gap-10 items-start">

        {/* ----- النص ----- */}
        <div className="text-left">
          <h2
            style={{
              fontFamily: "Sora",
              fontWeight: 600,
              fontStyle: "SemiBold",
              fontSize: "36px",
              lineHeight: "150%",
              letterSpacing: "0%",
              color: "#B3261E",
            }}
            className="mb-6"
          >
            Geomagnetic Storm
          </h2>

          <p
            style={{
              fontFamily: "Sora",
              fontWeight: 400,
              fontStyle: "Regular",
              fontSize: "16px",
              lineHeight: "36px",
              letterSpacing: "0%",
              verticalAlign: "bottom",
              color: "#3F3F3F",
            }}
            className="leading-normal text-left"
          >
            The phenomenon causing the greatest disturbance in the magnetosphere
            is called a ‘geomagnetic storm.’ It occurs when a vast amount of solar
            wind energy is injected into the magnetosphere by a strong southward IMF
            and high-speed solar wind. It is accompanied by various phenomena such
            as the promotion of magnetospheric convection, multiple occurrences of
            large aurora storms, increased plasma injection 
          </p>
        </div>

        {/* ----- الصورة ----- */}
        <div className="w-full flex justify-center">
          <img
            src={magneto3}
            alt="Geomagnetic storm illustration"
            className="w-full h-auto object-contain rounded-lg xl:mt-4 lg:mt-4"
          />
        </div>
      </div>

      {/* ----- الفقرة الكبيرة تحت الصورة وتمتد لنهاية الصفحة ----- */}
      <div className="mt-10 flex justify-center">
        <p
          style={{
            width: "1300px",
            fontFamily: "Sora",
            fontWeight: 400,
            fontStyle: "Regular",
            fontSize: "16px",
            lineHeight: "36px",
            letterSpacing: "0%",
            verticalAlign: "bottom",
            color: "#3F3F3F",
          }}
          className="text-left"
        >
          into the inner magnetosphere, acceleration/thermalization of plasma particles
          in the inner magnetosphere, which enhance the ring current, and disappearance/
          restoration of the radiation belt. Geomagnetic storms are categorized into two
          types depending on the solar wind structure that generates it. One is generated
          by CME. The other is generated by high-speed solar wind originating from the
          coronal hole. A strong shock wave is mostly formed in front of the magnetic
          cloud of a CME because the high-speed flow of the CME sweeps the low-speed solar
          wind. When it collides with the magnetosphere, it compresses the magnetosphere
          rapidly. The scale of the geomagnetic storm depends on the strength of the IMF
          and whether or not the IMF direction is southward in a magnetic cloud. Because
          the magnetic polarity of the IMF rotates from northward to southward through a
          magnetic cloud, a geomagnetic storm occurs in many cases when the CME collides
          with the magnetosphere. However, when the CME or the solar wind does not
          increase in speed and the southward IMF is relatively weak, no geomagnetic
          storm occurs. Additionally, geomagnetic storms with or without the compression
          of the magnetosphere are called ‘sudden commencement types’ and ‘gradual
          commencement types’, respectively. The development of a ring current is
          indicated by a decrease in the north–south geomagnetic field component at low
          and middle latitudes.
        </p>
      </div>

    </section>
  );
}
