import React from "react";
import magimg1 from "../../../assets/magimg1.png";
import Logo2 from "../../../components/logo2";

const Magneto1 = () => {
  return (
    <section className="relative w-full bg-[#faf7fb] py-24 px-6 lg:px-20 overflow-hidden">

      {/* 🔹 اللوجو — صغير على الموبايل وكامل الحجم على الشاشات الأكبر */}
      <div className="absolute top-4 right-4 z-50 scale-75 md:scale-100">
        <Logo2 />
      </div>

      <div className="max-w-7xl mx-auto grid grid-cols-1 lg:grid-cols-2 gap-10 items-start">

        {/* النص */}
        <div>
          <h4 className="tracking-[0.5em] text-[#9b1c1c] font-semibold mb-2">
            M A G N E T O S P H E R E
          </h4>

          <h1 className="text-4xl font-bold mb-6">Magnetosphere</h1>

          <p className="text-gray-700 leading-[1.9] text-[17px]">
            Earth is one of the magnetized planets. Earth’s intrinsic magnetic
            field is generated by electric currents inside the outer core, and
            it has the S and N poles at the north and south poles, respectively,
            as can be seen from the fact that the needles of compasses point to
            the north almost everywhere on the ground.
          </p>
        </div>

        {/* الصورة */}
        <div className="flex justify-center lg:justify-end">
          <img
            src={magimg1}
            alt="Magnetosphere"
            className="rounded-lg shadow-md w-full max-w-[600px] h-auto"
          />
        </div>
      </div>

      {/* الفقرة الثانية */}
      <div className="max-w-5xl mx-auto mt-20">
        <p className="text-gray-700 leading-[1.9] text-[17px]">
          The motion of charged particles, such as electrons and ions (plasmas),
          is changed by Earth’s magnetic field. As a result, high-energy charged
          particles associated with cosmic rays and proton phenomena (SEPs)
          cannot easily reach the middle- and low-latitude regions. In other
          words, Earth's magnetic field acts as a barrier to such high-energy
          particles in outer space. Earth's magnetic field does not extend
          infinitely but is deformed by the solar wind, forming a comet-like
          structure. We call this structure Earth’s magnetosphere. The condition
          of the magnetosphere is markedly changed by the solar wind.
        </p>
      </div>
    </section>
  );
};

export default Magneto1;
